const books = [
  {
    title: "The Silent Horizon",
    author: "James Carter",
    description: "A suspenseful journey across a future where humanity survives on floating cities.",
    coverImagePublicId: "books/silent-horizon",
    coverImage: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=400&h=600&fit=crop",
    genre: ["Science Fiction", "Thriller"],
    language: "English",
    pages: 342,
    publishedYear: 2021,
    price: 14.99
  },
  {
    title: "Echoes of the Past",
    author: "Amelia Wright",
    description: "A historical novel uncovering secrets buried across generations.",
    coverImagePublicId: "books/echoes-past",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
    genre: ["Historical", "Drama"],
    language: "English",
    pages: 410,
    publishedYear: 2018,
    price: 16.99
  },
  {
    title: "Code & Coffee",
    author: "Rohan Mehta",
    description: "Short stories about developers, startups, and midnight debugging sessions.",
    coverImagePublicId: "books/code-coffee",
    coverImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=600&fit=crop",
    genre: ["Technology", "Short Stories"],
    language: "English",
    pages: 198,
    publishedYear: 2022,
    price: 12.99
  },
  {
    title: "Desert Bloom",
    author: "Fatima Noor",
    description: "A poetic exploration of love and survival in harsh landscapes.",
    coverImagePublicId: "books/desert-bloom",
    coverImage: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop",
    genre: ["Poetry", "Romance"],
    language: "English",
    pages: 156,
    publishedYear: 2019,
    price: 11.99
  },
  {
    title: "The Last Algorithm",
    author: "Victor Han",
    description: "An AI researcher faces the unintended consequences of his creation.",
    coverImagePublicId: "books/last-algorithm",
    coverImage: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=600&fit=crop",
    genre: ["Science Fiction", "Technology"],
    language: "English",
    pages: 376,
    publishedYear: 2023,
    price: 15.99
  },

  {
    title: "Midnight Train to Oslo",
    author: "Lars Henriksen",
    description: "A noir mystery unfolding during a single winter night.",
    coverImagePublicId: "books/midnight-oslo",
    coverImage: "https://images.unsplash.com/photo-1568667256549-094345857637?w=400&h=600&fit=crop",
    genre: ["Mystery", "Crime"],
    language: "English",
    pages: 289,
    publishedYear: 2017,
    price: 13.99
  },
  {
    title: "Wild Roots",
    author: "Sophie Green",
    description: "A guide to rediscovering nature in modern urban life.",
    coverImagePublicId: "books/wild-roots",
    coverImage: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=600&fit=crop",
    genre: ["Non-fiction", "Nature"],
    language: "English",
    pages: 224,
    publishedYear: 2020,
    price: 13.99
  },
  {
    title: "The Ember Crown",
    author: "Nathan Cole",
    description: "A fallen kingdom rises again through fire and rebellion.",
    coverImagePublicId: "books/ember-crown",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=600&fit=crop",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    pages: 512,
    publishedYear: 2016,
    price: 18.99
  },
  {
    title: "Fragments of Her",
    author: "Isabella Moore",
    description: "A psychological drama about memory, loss, and healing.",
    coverImagePublicId: "books/fragments-her",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
    genre: ["Drama", "Psychological"],
    language: "English",
    pages: 301,
    publishedYear: 2019,
    price: 14.99
  },
  {
    title: "Startup Myths",
    author: "Daniel Brooks",
    description: "Debunking common misconceptions about entrepreneurship.",
    coverImagePublicId: "books/startup-myths",
    coverImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=600&fit=crop",
    genre: ["Business", "Self-help"],
    language: "English",
    pages: 260,
    publishedYear: 2021,
    price: 15.99
  },

  {
    title: "Beyond the Reef",
    author: "Hannah Lee",
    description: "A marine biologist uncovers secrets beneath the ocean.",
    coverImagePublicId: "books/beyond-reef",
    coverImage: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=600&fit=crop",
    genre: ["Adventure", "Science"],
    language: "English",
    pages: 334,
    publishedYear: 2015,
    price: 14.99
  },
  {
    title: "Paper Cranes",
    author: "Kenji Sato",
    description: "A quiet novel about tradition, family, and change.",
    coverImagePublicId: "books/paper-cranes",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    genre: ["Literary Fiction"],
    language: "English",
    pages: 278,
    publishedYear: 2014,
    price: 13.99
  },
  {
    title: "Debugging Life",
    author: "Ananya Rao",
    description: "Essays on balancing career, creativity, and burnout.",
    coverImagePublicId: "books/debugging-life",
    coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=600&fit=crop",
    genre: ["Essays", "Self-help"],
    language: "English",
    pages: 212,
    publishedYear: 2022,
    price: 12.99
  },
  {
    title: "Storm over Valenport",
    author: "Eric Dawson",
    description: "Naval warfare and political intrigue collide.",
    coverImagePublicId: "books/valenport",
    coverImage: "https://images.unsplash.com/photo-1489549132488-d00b7eee80f1?w=400&h=600&fit=crop",
    genre: ["Fantasy", "War"],
    language: "English",
    pages: 467,
    publishedYear: 2018,
    price: 17.99
  },
  {
    title: "The Glass Library",
    author: "Mira Patel",
    description: "A magical library where books rewrite reality.",
    coverImagePublicId: "books/glass-library",
    coverImage: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400&h=600&fit=crop",
    genre: ["Fantasy", "Magical Realism"],
    language: "English",
    pages: 389,
    publishedYear: 2020,
    price: 16.99
  },

  {
    title: "Cold Case: Redwood",
    author: "Thomas Blake",
    description: "A detective reopens a decades-old murder case.",
    coverImagePublicId: "books/coldcase-redwood",
    coverImage: "https://images.unsplash.com/photo-1511316695145-4992006ffddb?w=400&h=600&fit=crop",
    genre: ["Crime", "Thriller"],
    language: "English",
    pages: 355,
    publishedYear: 2016,
    price: 14.99
  },
  {
    title: "Letters Never Sent",
    author: "Clara Nguyen",
    description: "Unsent letters reveal a lifetime of hidden emotions.",
    coverImagePublicId: "books/letters-never-sent",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop",
    genre: ["Romance", "Drama"],
    language: "English",
    pages: 244,
    publishedYear: 2019,
    price: 13.99
  },
  {
    title: "Quantum Roads",
    author: "Dr. Alan Price",
    description: "Popular science explaining modern physics concepts.",
    coverImagePublicId: "books/quantum-roads",
    coverImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=600&fit=crop",
    genre: ["Science", "Non-fiction"],
    language: "English",
    pages: 318,
    publishedYear: 2021,
    price: 15.99
  },
  {
    title: "The Painted Sky",
    author: "Lucia Fernandez",
    description: "A coming-of-age story set in rural Spain.",
    coverImagePublicId: "books/painted-sky",
    coverImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=600&fit=crop",
    genre: ["Drama"],
    language: "English",
    pages: 287,
    publishedYear: 2013,
    price: 12.99
  },
  {
    title: "Iron & Ash",
    author: "Markus Volkov",
    description: "A dystopian tale of survival in an industrial wasteland.",
    coverImagePublicId: "books/iron-ash",
    coverImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&h=600&fit=crop",
    genre: ["Dystopian", "Science Fiction"],
    language: "English",
    pages: 401,
    publishedYear: 2024,
    price: 16.99
  },

  {
    title: "Minimal Living",
    author: "Sarah Collins",
    description: "A practical guide to decluttering life and mind.",
    coverImagePublicId: "books/minimal-living",
    coverImage: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=600&fit=crop",
    genre: ["Lifestyle", "Self-help"],
    language: "English",
    pages: 190,
    publishedYear: 2020,
    price: 11.99
  },
  {
    title: "Under the Banyan Tree",
    author: "Rajiv Malhotra",
    description: "Stories inspired by small-town Indian life.",
    coverImagePublicId: "books/banyan-tree",
    coverImage: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=600&fit=crop",
    genre: ["Short Stories"],
    language: "English",
    pages: 230,
    publishedYear: 2017,
    price: 12.99
  },
  {
    title: "Neon Nights",
    author: "Alexa Stone",
    description: "Cyberpunk adventures in a glowing megacity.",
    coverImagePublicId: "books/neon-nights",
    coverImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=600&fit=crop",
    genre: ["Cyberpunk", "Science Fiction"],
    language: "English",
    pages: 362,
    publishedYear: 2022,
    price: 15.99
  },
  {
    title: "The Orchard Keeper",
    author: "William Frost",
    description: "A slow, reflective novel about land and legacy.",
    coverImagePublicId: "books/orchard-keeper",
    coverImage: "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=600&fit=crop",
    genre: ["Literary Fiction"],
    language: "English",
    pages: 295,
    publishedYear: 2011,
    price: 13.99
  },
  {
    title: "Moonlit Dunes",
    author: "Aisha Karim",
    description: "A forbidden romance set in the desert.",
    coverImagePublicId: "books/moonlit-dunes",
    coverImage: "https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?w=400&h=600&fit=crop",
    genre: ["Romance"],
    language: "English",
    pages: 268,
    publishedYear: 2018,
    price: 13.99
  },

  {
    title: "Data Structures Demystified",
    author: "Kevin Liu",
    description: "An accessible guide to core computer science concepts.",
    coverImagePublicId: "books/ds-demystified",
    coverImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=600&fit=crop",
    genre: ["Education", "Technology"],
    language: "English",
    pages: 445,
    publishedYear: 2023,
    price: 19.99
  },
  {
    title: "The Final Exhibit",
    author: "Olivia Hart",
    description: "A museum curator uncovers a dangerous secret.",
    coverImagePublicId: "books/final-exhibit",
    coverImage: "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=400&h=600&fit=crop",
    genre: ["Mystery", "Thriller"],
    language: "English",
    pages: 320,
    publishedYear: 2019,
    price: 14.99
  },
  {
    title: "Broken Compass",
    author: "Noah Reed",
    description: "A travel memoir about getting lost to be found.",
    coverImagePublicId: "books/broken-compass",
    coverImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=600&fit=crop",
    genre: ["Travel", "Memoir"],
    language: "English",
    pages: 275,
    publishedYear: 2016,
    price: 13.99
  },
  {
    title: "Ashes of Tomorrow",
    author: "Lena Kovacs",
    description: "Climate collapse and human resilience collide.",
    coverImagePublicId: "books/ashes-tomorrow",
    coverImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=400&h=600&fit=crop",
    genre: ["Climate Fiction"],
    language: "English",
    pages: 388,
    publishedYear: 2024,
    price: 16.99
  },
  {
    title: "The Small Things",
    author: "Emily Parker",
    description: "A heartwarming look at everyday miracles.",
    coverImagePublicId: "books/small-things",
    coverImage: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=400&h=600&fit=crop",
    genre: ["Feel-good", "Drama"],
    language: "English",
    pages: 214,
    publishedYear: 2015,
    price: 12.99
  },
  {
    title: "Whispers in the Fog",
    author: "Eleanor White",
    description: "A coastal town mystery where every secret hides in the mist.",
    coverImagePublicId: "books/whispers-fog",
    coverImage: "https://images.unsplash.com/photo-1487700160041-babef9c3cb55?w=400&h=600&fit=crop",
    genre: ["Mystery", "Thriller"],
    language: "English",
    pages: 336,
    publishedYear: 2017,
    price: 14.99
  },
  {
    title: "The Atlas of Forgotten Places",
    author: "Marco Bellini",
    description: "A journey through abandoned cities and lost civilizations.",
    coverImagePublicId: "books/forgotten-atlas",
    coverImage: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=400&h=600&fit=crop",
    genre: ["Travel", "History"],
    language: "English",
    pages: 418,
    publishedYear: 2019,
    price: 17.99
  },
  {
    title: "Binary Souls",
    author: "Nina Volkov",
    description: "When human consciousness merges with machines, love finds a new form.",
    coverImagePublicId: "books/binary-souls",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=600&fit=crop",
    genre: ["Science Fiction", "Romance"],
    language: "English",
    pages: 354,
    publishedYear: 2023,
    price: 15.99
  },
  {
    title: "The Quiet Battlefield",
    author: "Samuel Ortega",
    description: "A war story told through the lives of those left behind.",
    coverImagePublicId: "books/quiet-battlefield",
    coverImage: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400&h=600&fit=crop",
    genre: ["War", "Drama"],
    language: "English",
    pages: 392,
    publishedYear: 2016,
    price: 16.99
  },
  {
    title: "Roots and Rivers",
    author: "Maya Deshpande",
    description: "Interwoven stories of migration, memory, and identity.",
    coverImagePublicId: "books/roots-rivers",
    coverImage: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=400&h=600&fit=crop",
    genre: ["Literary Fiction", "Drama"],
    language: "English",
    pages: 281,
    publishedYear: 2018,
    price: 14.99
  },
  {
    title: "The Clockmaker's Secret",
    author: "Julian Frost",
    description: "A steampunk mystery hidden inside a city powered by gears.",
    coverImagePublicId: "books/clockmaker-secret",
    coverImage: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=400&h=600&fit=crop",
    genre: ["Steampunk", "Mystery"],
    language: "English",
    pages: 367,
    publishedYear: 2020,
    price: 15.99
  },
  {
    title: "Tides of Glass",
    author: "Helena Brooks",
    description: "A fragile world where oceans are both refuge and threat.",
    coverImagePublicId: "books/tides-glass",
    coverImage: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=400&h=600&fit=crop",
    genre: ["Climate Fiction", "Science Fiction"],
    language: "English",
    pages: 405,
    publishedYear: 2024,
    price: 16.99
  },
  {
    title: "The Language of Silence",
    author: "Omar Haddad",
    description: "A philosophical exploration of grief, faith, and meaning.",
    coverImagePublicId: "books/language-silence",
    coverImage: "https://images.unsplash.com/photo-1472173148041-00294f0814a2?w=400&h=600&fit=crop",
    genre: ["Philosophy", "Non-fiction"],
    language: "English",
    pages: 248,
    publishedYear: 2015,
    price: 14.99
  },
  {
    title: "Runes of the North",
    author: "Freya Lund",
    description: "Ancient magic awakens beneath frozen mountains.",
    coverImagePublicId: "books/runes-north",
    coverImage: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=400&h=600&fit=crop",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    pages: 489,
    publishedYear: 2017,
    price: 18.99
  },
  {
    title: "Built to Last",
    author: "Andrew Mitchell",
    description: "Lessons on resilience, leadership, and long-term thinking.",
    coverImagePublicId: "books/built-to-last",
    coverImage: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400&h=600&fit=crop",
    genre: ["Business", "Self-help"],
    language: "English",
    pages: 263,
    publishedYear: 2021,
    price: 15.99
  },

  {
    title: "The Final Lighthouse",
    author: "Grace O'Connell",
    description: "A solitary lighthouse keeper confronts the end of an era.",
    coverImagePublicId: "books/final-lighthouse",
    coverImage: "https://images.unsplash.com/photo-1513002749550-c59d786b8e6c?w=400&h=600&fit=crop",
    genre: ["Literary Fiction"],
    language: "English",
    pages: 297,
    publishedYear: 2014,
    price: 13.99
  },
  {
    title: "Signals from Orion",
    author: "Dr. Peter Lawson",
    description: "First contact forces humanity to question its place in the universe.",
    coverImagePublicId: "books/signals-orion",
    coverImage: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400&h=600&fit=crop",
    genre: ["Science Fiction", "Space Opera"],
    language: "English",
    pages: 432,
    publishedYear: 2022,
    price: 17.99
  },
  {
    title: "The Ink Beneath the Skin",
    author: "Valentina Russo",
    description: "Art, rebellion, and identity collide in modern Rome.",
    coverImagePublicId: "books/ink-beneath-skin",
    coverImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=600&fit=crop",
    genre: ["Contemporary", "Drama"],
    language: "English",
    pages: 319,
    publishedYear: 2019,
    price: 14.99
  },
  {
    title: "After the Last Snow",
    author: "Jonah Kim",
    description: "Survival and hope in a world facing sudden climate collapse.",
    coverImagePublicId: "books/last-snow",
    coverImage: "https://images.unsplash.com/photo-1491466424936-e304919aada7?w=400&h=600&fit=crop",
    genre: ["Dystopian", "Climate Fiction"],
    language: "English",
    pages: 371,
    publishedYear: 2024,
    price: 16.99
  },
  {
    title: "The Cartographer's Dream",
    author: "Isabel Moreno",
    description: "Maps that reshape the world fall into the wrong hands.",
    coverImagePublicId: "books/cartographers-dream",
    coverImage: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=400&h=600&fit=crop",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    pages: 458,
    publishedYear: 2016,
    price: 18.99
  },
  {
    title: "Hard Reset",
    author: "Lucas Bennett",
    description: "A burned-out engineer rebuilds his life after total collapse.",
    coverImagePublicId: "books/hard-reset",
    coverImage: "https://images.unsplash.com/photo-1496950866446-3253e1470e8e?w=400&h=600&fit=crop",
    genre: ["Contemporary", "Drama"],
    language: "English",
    pages: 284,
    publishedYear: 2021,
    price: 14.99
  },
  {
    title: "Gardens of Dust",
    author: "Noura Al-Fayed",
    description: "Hope and beauty grow in the ruins of a forgotten city.",
    coverImagePublicId: "books/gardens-dust",
    coverImage: "https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=400&h=600&fit=crop",
    genre: ["Literary Fiction"],
    language: "English",
    pages: 333,
    publishedYear: 2018,
    price: 14.99
  },
  {
    title: "The Long Way Home",
    author: "Patrick O'Sullivan",
    description: "A father and son reconnect during a cross-country journey.",
    coverImagePublicId: "books/long-way-home",
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=600&fit=crop",
    genre: ["Family", "Drama"],
    language: "English",
    pages: 266,
    publishedYear: 2015,
    price: 13.99
  },
  {
    title: "Threads of Fate",
    author: "Zara Khan",
    description: "Lives intertwine as destiny quietly reshapes their paths.",
    coverImagePublicId: "books/threads-fate",
    coverImage: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop",
    genre: ["Romance", "Drama"],
    language: "English",
    pages: 341,
    publishedYear: 2020,
    price: 15.99
  },
  {
    title: "Edge of the Singularity",
    author: "Caleb Turner",
    description: "The moment before AI surpasses humanity changes everything.",
    coverImagePublicId: "books/edge-singularity",
    coverImage: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
    genre: ["Science Fiction", "Technology"],
    language: "English",
    pages: 398,
    publishedYear: 2025,
    price: 17.99
  }

];

export default books;